[project]
name = "track-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiortc>=1.13.0",
    "fastapi>=0.115.12",
    "lap>=0.5.12",
    "ultralytics>=8.3.145",
    "uvicorn[standard]>=0.34.2",
]
